@php($selectedMembers = old('member_ids', isset($project) ? $project->members->pluck('id')->all() : []))
<div class="grid grid-cols-1 gap-5 md:grid-cols-2">
    <div class="md:col-span-2"><x-input-label for="name" value="Nama project"/><x-text-input id="name" name="name" class="mt-1 block w-full" :value="old('name', $project->name ?? '')" required autofocus/><x-input-error :messages="$errors->get('name')" class="mt-2"/></div>
    <div><x-input-label for="client_id" value="Pelanggan"/><select id="client_id" name="client_id" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"><option value="">Tanpa pelanggan</option>@foreach($clients as $client)<option value="{{ $client->id }}" @selected(old('client_id', $project->client_id ?? '') == $client->id)>{{ $client->company_name }}</option>@endforeach</select></div>
    <div><x-input-label for="status" value="Status"/><select id="status" name="status" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm">@foreach(['not_started' => 'Belum dimulai', 'in_progress' => 'Berjalan', 'on_hold' => 'Ditunda', 'completed' => 'Selesai', 'cancelled' => 'Dibatalkan'] as $value => $label)<option value="{{ $value }}" @selected(old('status', $project->status ?? 'not_started') === $value)>{{ $label }}</option>@endforeach</select></div>
    <div><x-input-label for="start_date" value="Tanggal mulai"/><x-text-input id="start_date" name="start_date" type="date" class="mt-1 block w-full" :value="old('start_date', isset($project) && $project->start_date ? $project->start_date->toDateString() : '')"/></div>
    <div><x-input-label for="deadline" value="Tenggat"/><x-text-input id="deadline" name="deadline" type="date" class="mt-1 block w-full" :value="old('deadline', isset($project) && $project->deadline ? $project->deadline->toDateString() : '')"/></div>
    <div><x-input-label for="billing_type" value="Tipe penagihan"/><select id="billing_type" name="billing_type" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm">@foreach(['not_billed' => 'Tidak ditagihkan', 'fixed' => 'Harga tetap', 'hourly' => 'Per jam'] as $value => $label)<option value="{{ $value }}" @selected(old('billing_type', $project->billing_type ?? 'not_billed') === $value)>{{ $label }}</option>@endforeach</select></div>
    <div><x-input-label for="budget" value="Anggaran"/><x-text-input id="budget" name="budget" type="number" min="0" step="0.01" class="mt-1 block w-full" :value="old('budget', $project->budget ?? 0)"/></div>
    <div class="md:col-span-2"><x-input-label for="description" value="Deskripsi"/><textarea id="description" name="description" rows="5" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm">{{ old('description', $project->description ?? '') }}</textarea></div>
    <div class="md:col-span-2"><x-input-label value="Anggota project"/><div class="mt-2 grid grid-cols-2 gap-2 md:grid-cols-3">@foreach($staff as $member)<label class="flex items-center gap-2 text-sm"><input type="checkbox" name="member_ids[]" value="{{ $member->id }}" @checked(in_array($member->id, $selectedMembers)) class="rounded border-gray-300 text-indigo-600 shadow-sm">{{ $member->name }}</label>@endforeach</div></div>
</div>
<div class="mt-6 flex gap-3"><x-primary-button>{{ isset($project) ? 'Simpan perubahan' : 'Buat project' }}</x-primary-button><a href="{{ isset($project) ? route('projects.show', $project) : route('projects.index') }}" class="rounded-md px-4 py-2 text-sm text-gray-600">Batal</a></div>
