@php($selectedRoles = old('roles', $staff->exists ? $staff->roles->pluck('name')->all() : []))
<div class="grid grid-cols-1 gap-5 md:grid-cols-2">
    <div><x-input-label for="name" value="Nama staff" /><x-text-input id="name" name="name" type="text" class="mt-1 block w-full" :value="old('name', $staff->name)" required autofocus /><x-input-error :messages="$errors->get('name')" class="mt-2" /></div>
    <div><x-input-label for="email" value="Email staff" /><x-text-input id="email" name="email" type="email" class="mt-1 block w-full" :value="old('email', $staff->email)" required /><x-input-error :messages="$errors->get('email')" class="mt-2" /></div>
    <div><x-input-label for="password" :value="$staff->exists ? 'Password baru (opsional)' : 'Password'" /><x-text-input id="password" name="password" type="password" class="mt-1 block w-full" :required="! $staff->exists" /><x-input-error :messages="$errors->get('password')" class="mt-2" /></div>
    <div><x-input-label for="password_confirmation" value="Konfirmasi password" /><x-text-input id="password_confirmation" name="password_confirmation" type="password" class="mt-1 block w-full" :required="! $staff->exists" /></div>
</div>
<fieldset class="mt-6"><legend class="text-sm font-medium text-gray-700">Role</legend><div class="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">@foreach ($roles as $role)<label class="flex items-center gap-2 rounded-md border border-gray-200 px-3 py-2 text-sm text-gray-700"><input type="checkbox" name="roles[]" value="{{ $role->name }}" class="rounded border-gray-300 text-indigo-600 shadow-sm focus:ring-indigo-500" @checked(in_array($role->name, $selectedRoles, true))> {{ $role->name }}</label>@endforeach</div><x-input-error :messages="$errors->get('roles')" class="mt-2" /></fieldset>
<label class="mt-6 inline-flex items-center gap-2 text-sm text-gray-700"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" class="rounded border-gray-300 text-indigo-600 shadow-sm focus:ring-indigo-500" @checked(old('is_active', $staff->exists ? $staff->is_active : true))> Akun aktif dan dapat login</label>
<div class="mt-6 flex items-center gap-3"><x-primary-button>{{ $staff->exists ? 'Simpan perubahan' : 'Buat akun staff' }}</x-primary-button><a href="{{ route('staff.index') }}" class="text-sm font-medium text-gray-600 hover:text-gray-900">Batal</a></div>
