<div class="grid grid-cols-1 gap-5 md:grid-cols-2">
    <div class="md:col-span-2"><x-input-label for="subject" value="Subjek"/><x-text-input id="subject" name="subject" class="mt-1 block w-full" :value="old('subject', $ticket->subject ?? '')" required autofocus/><x-input-error :messages="$errors->get('subject')" class="mt-2"/></div>
    <div><x-input-label for="client_id" value="Pelanggan"/><select id="client_id" name="client_id" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"><option value="">Tanpa pelanggan</option>@foreach($clients as $client)<option value="{{ $client->id }}" @selected(old('client_id', $ticket->client_id ?? '') == $client->id)>{{ $client->company_name }}</option>@endforeach</select></div>
    <div><x-input-label for="contact_id" value="Kontak"/><select id="contact_id" name="contact_id" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"><option value="">Tanpa kontak</option>@foreach($contacts as $contact)<option value="{{ $contact->id }}" @selected(old('contact_id', $ticket->contact_id ?? '') == $contact->id)>{{ $contact->first_name }} {{ $contact->last_name }} — {{ $contact->client->company_name }}</option>@endforeach</select></div>
    <div><x-input-label for="department_id" value="Departemen"/><select id="department_id" name="department_id" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"><option value="">Tanpa departemen</option>@foreach($departments as $department)<option value="{{ $department->id }}" @selected(old('department_id', $ticket->department_id ?? '') == $department->id)>{{ $department->name }}</option>@endforeach</select></div>
    <div><x-input-label for="assigned_to" value="Ditugaskan kepada"/><select id="assigned_to" name="assigned_to" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"><option value="">Belum ditugaskan</option>@foreach($staff as $member)<option value="{{ $member->id }}" @selected(old('assigned_to', $ticket->assigned_to ?? '') == $member->id)>{{ $member->name }}</option>@endforeach</select></div>
    <div><x-input-label for="priority" value="Prioritas"/><select id="priority" name="priority" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm">@foreach(['low' => 'Rendah', 'medium' => 'Sedang', 'high' => 'Tinggi', 'urgent' => 'Mendesak'] as $value => $label)<option value="{{ $value }}" @selected(old('priority', $ticket->priority ?? 'medium') === $value)>{{ $label }}</option>@endforeach</select></div>
    <div><x-input-label for="status" value="Status"/><select id="status" name="status" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm">@foreach(['open' => 'Terbuka', 'in_progress' => 'Diproses', 'answered' => 'Dijawab', 'closed' => 'Ditutup'] as $value => $label)<option value="{{ $value }}" @selected(old('status', $ticket->status ?? 'open') === $value)>{{ $label }}</option>@endforeach</select></div>
    @if(!isset($ticket))<div class="md:col-span-2"><x-input-label for="message" value="Pesan awal"/><textarea id="message" name="message" rows="5" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm">{{ old('message') }}</textarea></div>@endif
</div>
<div class="mt-6 flex gap-3"><x-primary-button>{{ isset($ticket) ? 'Simpan perubahan' : 'Buat ticket' }}</x-primary-button><a href="{{ isset($ticket) ? route('tickets.show', $ticket) : route('tickets.index') }}" class="rounded-md px-4 py-2 text-sm text-gray-600">Batal</a></div>
