@csrf
<div class="grid grid-cols-1 gap-5 md:grid-cols-2">
    <div><x-input-label for="name" value="Nama lead" /><x-text-input id="name" name="name" type="text" class="mt-1 block w-full" :value="old('name', $lead->name ?? '')" required autofocus /><x-input-error :messages="$errors->get('name')" class="mt-2" /></div>
    <div><x-input-label for="company_name" value="Perusahaan" /><x-text-input id="company_name" name="company_name" type="text" class="mt-1 block w-full" :value="old('company_name', $lead->company_name ?? '')" /><x-input-error :messages="$errors->get('company_name')" class="mt-2" /></div>
    <div><x-input-label for="email" value="Email" /><x-text-input id="email" name="email" type="email" class="mt-1 block w-full" :value="old('email', $lead->email ?? '')" /><x-input-error :messages="$errors->get('email')" class="mt-2" /></div>
    <div><x-input-label for="phone" value="Telepon" /><x-text-input id="phone" name="phone" type="text" class="mt-1 block w-full" :value="old('phone', $lead->phone ?? '')" /><x-input-error :messages="$errors->get('phone')" class="mt-2" /></div>
    <div><x-input-label for="source_id" value="Sumber" /><select id="source_id" name="source_id" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"><option value="">Tidak diketahui</option>@foreach($sources as $source)<option value="{{ $source->id }}" @selected((string) old('source_id', $lead->source_id ?? '') === (string) $source->id)>{{ $source->name }}</option>@endforeach</select><x-input-error :messages="$errors->get('source_id')" class="mt-2" /></div>
    <div><x-input-label for="status_id" value="Status" /><select id="status_id" name="status_id" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm" required>@foreach($statuses as $status)<option value="{{ $status->id }}" @selected((string) old('status_id', $lead->status_id ?? $statuses->firstWhere('is_default', true)?->id) === (string) $status->id)>{{ $status->name }}</option>@endforeach</select><x-input-error :messages="$errors->get('status_id')" class="mt-2" /></div>
    <div><x-input-label for="assigned_to" value="Staf penanggung jawab" /><select id="assigned_to" name="assigned_to" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"><option value="">Belum ditugaskan</option>@foreach($staff as $member)<option value="{{ $member->id }}" @selected((string) old('assigned_to', $lead->assigned_to ?? '') === (string) $member->id)>{{ $member->name }}</option>@endforeach</select><x-input-error :messages="$errors->get('assigned_to')" class="mt-2" /></div>
    <div><x-input-label for="lead_value" value="Nilai estimasi" /><x-text-input id="lead_value" name="lead_value" type="number" min="0" step="0.01" class="mt-1 block w-full" :value="old('lead_value', $lead->lead_value ?? 0)" /><x-input-error :messages="$errors->get('lead_value')" class="mt-2" /></div>
    <div class="md:col-span-2"><x-input-label for="notes" value="Catatan" /><textarea id="notes" name="notes" rows="4" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm">{{ old('notes', $lead->notes ?? '') }}</textarea><x-input-error :messages="$errors->get('notes')" class="mt-2" /></div>
</div>
<div class="mt-6 flex items-center gap-3"><x-primary-button>{{ $submitLabel }}</x-primary-button><a href="{{ isset($lead) ? route('leads.show', $lead) : route('leads.index') }}" class="text-sm font-medium text-gray-600">Batal</a></div>
