@php($selectedAssignees = old('assignee_ids', isset($task) ? $task->assignees->pluck('id')->all() : []))
<div class="grid grid-cols-1 gap-5 md:grid-cols-2">
    <div class="md:col-span-2"><x-input-label for="name" value="Nama task"/><x-text-input id="name" name="name" class="mt-1 block w-full" :value="old('name', $task->name ?? '')" required autofocus/><x-input-error :messages="$errors->get('name')" class="mt-2"/></div>
    <div><x-input-label for="project_id" value="Project"/><select id="project_id" name="project_id" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"><option value="">Task mandiri</option>@foreach($projects as $projectOption)<option value="{{ $projectOption->id }}" @selected(old('project_id', isset($task) && $task->related instanceof App\Models\Project ? $task->related_id : request('project_id')) == $projectOption->id)>{{ $projectOption->name }}</option>@endforeach</select></div>
    <div><x-input-label for="milestone_id" value="Milestone"/><select id="milestone_id" name="milestone_id" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"><option value="">Tanpa milestone</option>@foreach($milestones as $milestone)<option value="{{ $milestone->id }}" @selected(old('milestone_id', $task->milestone_id ?? '') == $milestone->id)>{{ $milestone->project->name }} — {{ $milestone->title }}</option>@endforeach</select></div>
    @php($relatedType = old('related_type', isset($task) && $task->related ? match(get_class($task->related)) { App\Models\Lead::class => 'lead', App\Models\Client::class => 'client', default => null } : null))
    @php($relatedId = old('related_id', isset($task) && $relatedType ? $task->related_id : null))
    <div><x-input-label for="related_type" value="Relasi lain"/><select id="related_type" name="related_type" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"><option value="">Tidak ada</option><option value="lead" @selected($relatedType === 'lead')>Lead</option><option value="client" @selected($relatedType === 'client')>Pelangan</option></select></div>
    <div><x-input-label for="related_id" value="Data relasi"/><select id="related_id" name="related_id" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"><option value="">Pilih Lead atau Pelanggan</option><optgroup label="Lead">@foreach($leads as $lead)<option value="{{ $lead->id }}" @selected($relatedId == $lead->id)>{{ $lead->name }}</option>@endforeach</optgroup><optgroup label="Pelanggan">@foreach($clients as $client)<option value="{{ $client->id }}" @selected($relatedId == $client->id)>{{ $client->company_name }}</option>@endforeach</optgroup></select></div>
    <div><x-input-label for="status" value="Status"/><select id="status" name="status" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm">@foreach(['todo' => 'To do', 'in_progress' => 'Dikerjakan', 'testing' => 'Pengujian', 'completed' => 'Selesai', 'cancelled' => 'Dibatalkan'] as $value => $label)<option value="{{ $value }}" @selected(old('status', $task->status ?? 'todo') === $value)>{{ $label }}</option>@endforeach</select></div>
    <div><x-input-label for="priority" value="Prioritas"/><select id="priority" name="priority" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm">@foreach(['low' => 'Rendah', 'medium' => 'Sedang', 'high' => 'Tinggi', 'urgent' => 'Mendesak'] as $value => $label)<option value="{{ $value }}" @selected(old('priority', $task->priority ?? 'medium') === $value)>{{ $label }}</option>@endforeach</select></div>
    <div><x-input-label for="start_date" value="Tanggal mulai"/><x-text-input id="start_date" name="start_date" type="date" class="mt-1 block w-full" :value="old('start_date', isset($task) && $task->start_date ? $task->start_date->toDateString() : '')"/></div>
    <div><x-input-label for="due_date" value="Tenggat"/><x-text-input id="due_date" name="due_date" type="date" class="mt-1 block w-full" :value="old('due_date', isset($task) && $task->due_date ? $task->due_date->toDateString() : '')"/></div>
    <div class="md:col-span-2"><x-input-label for="description" value="Deskripsi"/><textarea id="description" name="description" rows="5" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm">{{ old('description', $task->description ?? '') }}</textarea></div>
    <div class="md:col-span-2"><x-input-label value="Penanggung jawab"/><div class="mt-2 grid grid-cols-2 gap-2 md:grid-cols-3">@foreach($staff as $member)<label class="flex items-center gap-2 text-sm"><input type="checkbox" name="assignee_ids[]" value="{{ $member->id }}" @checked(in_array($member->id, $selectedAssignees)) class="rounded border-gray-300 text-indigo-600 shadow-sm">{{ $member->name }}</label>@endforeach</div></div>
</div>
<div class="mt-6 flex gap-3"><x-primary-button>{{ isset($task) ? 'Simpan perubahan' : 'Buat task' }}</x-primary-button><a href="{{ isset($task) ? route('tasks.show', $task) : route('tasks.index') }}" class="rounded-md px-4 py-2 text-sm text-gray-600">Batal</a></div>
