<x-portal.layout :title="'Project '.$project->name">
    <div class="mx-auto max-w-5xl px-5">
        <a href="{{ route('portal.projects') }}" class="inline-flex items-center gap-2 text-sm font-semibold text-teal-700 transition hover:text-teal-900"><svg class="h-4 w-4" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true"><path fill-rule="evenodd" d="M17.5 10a.75.75 0 0 1-.75.75H5.06l3.97 3.97a.75.75 0 0 1-1.06 1.06l-5.25-5.25a.75.75 0 0 1 0-1.06l5.25-5.25a.75.75 0 0 1 1.06 1.06L5.06 9.25h11.69a.75.75 0 0 1 .75.75Z" clip-rule="evenodd" /></svg>Kembali ke daftar Project</a>
        <div class="mt-5 overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200">
            <div class="flex flex-col gap-5 border-b border-slate-200 px-6 py-6 sm:flex-row sm:items-start sm:justify-between"><div><p class="text-sm font-semibold text-slate-500">Project</p><h1 class="mt-1 text-2xl font-extrabold tracking-tight text-slate-900">{{ $project->name }}</h1><p class="mt-2 text-sm text-slate-500">Mulai {{ $project->start_date?->format('d M Y') ?? '—' }} · Tenggat {{ $project->deadline?->format('d M Y') ?? '—' }}</p></div><span class="inline-flex w-fit rounded-full bg-teal-50 px-3 py-1.5 text-sm font-bold text-teal-800">{{ str($project->status)->replace('_', ' ')->title() }}</span></div>
            <section class="border-b border-slate-200 bg-slate-50 px-6 py-5"><div class="flex items-end justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Progres project</p><p class="mt-1 text-2xl font-extrabold text-slate-900">{{ $project->progress }}%</p></div><p class="text-sm font-semibold text-slate-600">{{ $project->tasks->where('status', 'completed')->count() }} dari {{ $project->tasks->count() }} tugas selesai</p></div><div class="mt-4 h-3 overflow-hidden rounded-full bg-slate-200"><div class="h-full rounded-full bg-teal-600" style="width: {{ min(100, max(0, $project->progress)) }}%"></div></div></section>
            @if($project->description)<section class="border-b border-slate-200 px-6 py-6"><h2 class="text-base font-extrabold text-slate-900">Ringkasan project</h2><p class="mt-3 whitespace-pre-line text-sm leading-7 text-slate-600">{{ $project->description }}</p></section>@endif
            <section class="border-b border-slate-200 px-6 py-6"><h2 class="text-base font-extrabold text-slate-900">Milestone</h2><div class="mt-4 space-y-3">@forelse($project->milestones as $milestone)<article class="rounded-xl border border-slate-200 p-4"><div class="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><h3 class="font-bold text-slate-800">{{ $milestone->title }}</h3>@if($milestone->description)<p class="mt-1 text-sm leading-6 text-slate-600">{{ $milestone->description }}</p>@endif</div><span class="text-sm font-semibold text-slate-500">{{ $milestone->due_date?->format('d M Y') ?? '—' }}</span></div></article>@empty<p class="rounded-xl bg-slate-50 px-4 py-5 text-sm text-slate-500">Belum ada milestone yang dibagikan.</p>@endforelse</div></section>
            <section class="px-6 py-6"><h2 class="text-base font-extrabold text-slate-900">Tugas project</h2><div class="mt-4 overflow-x-auto rounded-xl border border-slate-200"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th class="px-4 py-3">Tugas</th><th class="px-4 py-3">Prioritas</th><th class="px-4 py-3">Tenggat</th><th class="px-4 py-3">Status</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($project->tasks as $task)<tr><td class="px-4 py-3.5 font-medium text-slate-800">{{ $task->name }}</td><td class="px-4 py-3.5 text-slate-600">{{ str($task->priority)->title() }}</td><td class="px-4 py-3.5 text-slate-600">{{ $task->due_date?->format('d M Y') ?? '—' }}</td><td class="px-4 py-3.5"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-700">{{ str($task->status)->replace('_', ' ')->title() }}</span></td></tr>@empty<tr><td colspan="4" class="px-4 py-8 text-center text-slate-500">Belum ada tugas yang dibagikan.</td></tr>@endforelse</tbody></table></div></section>
        </div>
    </div>
</x-portal.layout>
