<x-portal.layout title="Ticket">
    <div class="mx-auto max-w-7xl px-5">
        <div class="grid grid-cols-1 gap-6 lg:grid-cols-3">
            <section class="lg:col-span-2"><p class="text-sm font-semibold text-teal-700">Layanan pelanggan</p><h1 class="text-2xl font-extrabold tracking-tight text-slate-900">Ticket Dukungan</h1><p class="mt-1 text-sm text-slate-500">Buka ticket untuk melihat percakapan dan perkembangan penanganannya.</p>
                <div class="mt-6 overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Ticket</th><th class="px-5 py-3">Departemen</th><th class="px-5 py-3">Prioritas</th><th class="px-5 py-3">Status</th><th class="px-5 py-3"><span class="sr-only">Aksi</span></th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($tickets as $ticket)<tr class="transition hover:bg-slate-50"><td class="px-5 py-4"><p class="font-bold text-slate-800">{{ $ticket->subject }}</p><p class="mt-1 text-xs font-medium text-slate-500">{{ $ticket->number }}</p>@if($ticket->replies->first())<p class="mt-2 line-clamp-1 text-xs text-slate-600">{{ $ticket->replies->first()->message }}</p>@endif</td><td class="px-5 py-4 text-slate-600">{{ $ticket->department?->name ?? '—' }}</td><td class="px-5 py-4 text-slate-600">{{ str($ticket->priority)->title() }}</td><td class="px-5 py-4"><span class="rounded-full bg-teal-50 px-2.5 py-1 text-xs font-bold text-teal-800">{{ str($ticket->status)->replace('_', ' ')->title() }}</span></td><td class="px-5 py-4 text-right"><a href="{{ route('portal.tickets.show', $ticket) }}" class="inline-flex rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white transition hover:bg-teal-700">Lihat Detail</a></td></tr>@empty<tr><td colspan="5" class="px-5 py-10 text-center text-slate-500">Belum ada ticket.</td></tr>@endforelse</tbody></table></div></div><div class="mt-4">{{ $tickets->links() }}</div>
            </section>
            <aside class="h-fit rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 class="font-extrabold text-slate-900">Buat ticket baru</h2><p class="mt-1 text-sm text-slate-500">Jelaskan kebutuhan Anda, tim kami akan menindaklanjuti.</p><form method="POST" action="{{ route('portal.tickets.store') }}" class="mt-5 space-y-4">@csrf <div><x-input-label for="subject" value="Subjek"/><x-text-input id="subject" name="subject" class="mt-1 block w-full" required/></div><div><x-input-label for="department_id" value="Departemen"/><select id="department_id" name="department_id" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"><option value="">Pilih departemen</option>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select></div><div><x-input-label for="priority" value="Prioritas"/><select id="priority" name="priority" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"><option value="medium">Sedang</option><option value="low">Rendah</option><option value="high">Tinggi</option><option value="urgent">Mendesak</option></select></div><div><x-input-label for="message" value="Pesan"/><textarea id="message" name="message" rows="5" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm" required></textarea></div><x-primary-button>Kirim ticket</x-primary-button></form></aside>
        </div>
    </div>
</x-portal.layout>
