<x-portal.layout :title="'Ticket '.$ticket->number">
    <div class="mx-auto max-w-5xl px-5">
        <a href="{{ route('portal.tickets') }}" class="inline-flex items-center gap-2 text-sm font-semibold text-teal-700 transition hover:text-teal-900"><svg class="h-4 w-4" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true"><path fill-rule="evenodd" d="M17.5 10a.75.75 0 0 1-.75.75H5.06l3.97 3.97a.75.75 0 0 1-1.06 1.06l-5.25-5.25a.75.75 0 0 1 0-1.06l5.25-5.25a.75.75 0 0 1 1.06 1.06L5.06 9.25h11.69a.75.75 0 0 1 .75.75Z" clip-rule="evenodd" /></svg>Kembali ke daftar Ticket</a>
        <div class="mt-5 overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200">
            <div class="flex flex-col gap-5 border-b border-slate-200 px-6 py-6 sm:flex-row sm:items-start sm:justify-between"><div><p class="text-sm font-semibold text-slate-500">{{ $ticket->number }}</p><h1 class="mt-1 text-2xl font-extrabold tracking-tight text-slate-900">{{ $ticket->subject }}</h1></div><span class="inline-flex w-fit rounded-full bg-teal-50 px-3 py-1.5 text-sm font-bold text-teal-800">{{ str($ticket->status)->replace('_', ' ')->title() }}</span></div>
            <div class="grid gap-4 border-b border-slate-200 bg-slate-50 px-6 py-5 sm:grid-cols-3"><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Departemen</p><p class="mt-1 font-semibold text-slate-800">{{ $ticket->department?->name ?? '—' }}</p></div><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Prioritas</p><p class="mt-1 font-semibold text-slate-800">{{ str($ticket->priority)->title() }}</p></div><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Dibuat</p><p class="mt-1 font-semibold text-slate-800">{{ $ticket->created_at?->format('d M Y, H:i') ?? '—' }}</p></div></div>
            <section class="px-6 py-6"><h2 class="text-base font-extrabold text-slate-900">Percakapan</h2><div class="mt-5 space-y-4">@forelse($ticket->replies as $reply)<article class="rounded-xl border border-slate-200 p-4 {{ $reply->user_type === 'contact' ? 'bg-teal-50/50' : 'bg-white' }}"><div class="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between"><p class="text-sm font-bold text-slate-800">{{ $reply->user_type === 'contact' ? 'Anda' : 'Tim Aksi CRM' }}</p><time class="text-xs font-medium text-slate-400">{{ $reply->created_at?->format('d M Y, H:i') }}</time></div><p class="mt-3 whitespace-pre-line text-sm leading-6 text-slate-700">{{ $reply->message }}</p></article>@empty<p class="rounded-xl bg-slate-50 px-4 py-6 text-sm text-slate-500">Belum ada pesan yang dapat ditampilkan pada ticket ini.</p>@endforelse</div></section>
        </div>
    </div>
</x-portal.layout>
